### ISSUE TITLE
1.12 Crash on forge 2387

### ISSUE THREAD

**Issue by ElSaam** [Team-Fruit/SignPicture#20]
`The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SignPicture (signpic)`

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  SignPictureCorePlugin (SignPicture-1.12-2.7.1-universal.jar)
  BlurPlugin (Blur-1.0.2-10.jar)
  ItemPatchingLoader (ItemPhysic_Lite_1.3.6_mc1.12.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 6/29/17 10:08 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SignPicture (signpic)
Caused by: java.lang.NoClassDefFoundError: com/kamesuta/mc/signpic/render/CustomItemSignRenderer
	at com.kamesuta.mc.signpic.ClientProxy.preInit(ClientProxy.java:42)
	at com.kamesuta.mc.signpic.SignPicture.preInit(SignPicture.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:628)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.kamesuta.mc.signpic.render.CustomItemSignRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/IPerspectiveAwareModel
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.IPerspectiveAwareModel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 50 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 514543384 bytes (490 MB) / 1070596096 bytes (1021 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar) 
	UCH	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar) 
	UCH	itemphysic{1.4.0} [ItemPhysic] (minecraft.jar) 
	UCH	translatemod{4.3} [Real-time translation mod] ([1.12]RealTimeTranslation-4.3.jar) 
	UCH	ambientsounds{2.0.0} [AmbientSounds] (AmbientSounds v2.0.4 mc1.11.2  1.12.zip) 
	UCH	blur{1.0.2-10} [Blur] (Blur-1.0.2-10.jar) 
	UCH	fbp{2.2.2} [Fancy Block Particles] (FancyBlockParticles-1.12-2.2.2.jar) 
	UCH	mobends{0.23.4} [Mo' Bends] (mobends-0.23.4_for_MC-1.12.jar) 
	UCE	signpic{2.7.1} [SignPicture] (SignPicture-1.12-2.7.1-universal.jar) 
	Loaded coremods (and transformers): 
SignPictureCorePlugin (SignPicture-1.12-2.7.1-universal.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
BlurPlugin (Blur-1.0.2-10.jar)
  com.tterrag.blur.BlurTransformer
ItemPatchingLoader (ItemPhysic_Lite_1.3.6_mc1.12.jar)
  com.creativemd.itemphysic.ItemTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.33' Renderer: 'GeForce GTX 970/PCIe/SSE2'`

**Comment by BlackYamato** [comment]
SignPicture-1.12-2.8.0についても，Minecraft Forge-1.12-14.21.0.2348以降でクラッシュするようです。

クラッシュレポート
https://pastebin.com/Ryb87jKR

近頃は，Forge2348以降を要求するMODが出てきており，是非SignPictureと共に使用したいので，対応をよろしくお願い致します。

**Comment by NoplixDE** [comment]
Will there be a fix anytime soon?

**Comment by sjcl** [comment]
There are known bugs, but we can release it soon.

**Comment by NoplixDE** [comment]
Tested it in SP and everything seems to be working right! Thanks for the Update!

**Comment by NoplixDE** [comment]
Doesn't work on Server.

https://gist.github.com/NoplixDE/d2d0be249503f3d2c906e914b3bdcdcf

**Comment by sjcl** [comment]
SignPicture is not required for the server, but it is fixed in the next version.
