### ISSUE TITLE
 Crash when trying to change key

### ISSUE THREAD

**Issue by sousuke0422** [Team-Fruit/SignPicture#29]

**Comment by sjcl** [comment]
It is similar to #23 , is this a different phenomenon?

**Comment by sousuke0422** [comment]
It is very similar.

**Comment by Corosauce** [comment]
Still a thing in 1.12.2, heres my crashlog, on linux, try to change it from BACKSLASH to \ (yes, same key, but thats how i looked in mc when i changed it cause BACKSLASH wasnt working), am on linux.

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.kamesuta.mc.signpic.handler.KeyHandler$Key$AbstractKey.isKeyPressed(KeyHandler.java:49)
	at com.kamesuta.mc.signpic.handler.KeyHandler.onGuiKeyInput(KeyHandler.java:115)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full log: https://gist.githubusercontent.com/Corosauce/802c414b27ac069f7fe69b1c663a11f1/raw/0a58c27c78f312fc4434d38a602840cef9d7789d/gistfile1.txt

**Comment by poofcucumber** [comment]
Can someone answer this? Im still getting this issue.
